### ISSUE TITLE
Geist Force now works but only changing the controller options in menu

### ISSUE THREAD

**Issue by emersonnovais** [twinaphex/reicast-emulator#1105]
A single trick to made Geist Force working in Retroarch. I  don't know when the game become working but selecting by mistake a different controller type then worked.

The trick:
After loading the game by select the option "Game start", enter the Retroarch menu and in "controls" settings change the controller type to "arcade stick" and then the game boots. After that change again the controller to "controller" to input works correctly. 

I discover the trick in the last thursday after trying if the Geist Force New prototype version will works. I tested with the early prototype and works in the same way. I made a video to illustrate it:
https://www.youtube.com/watch?v=9o7dPw2BqaQ

*Capture was made with Kazam.

My system:
Ubuntu 18.04 64 bits
CPU: Intel Corei i5 460m
GPU: Nvidia 310m

**Comment by emersonnovais** [comment]
I tested this same trick with "Ghost Blade" but not worked and crashed with the SH4 exception

**Comment by flyinghead** [comment]
The Geist Force issue has been fixed in the dev branch
But this is a valid workaround until the dev branch is merged.

**Comment by emersonnovais** [comment]
I will close the issue
