### ISSUE TITLE
Lightgun Flycast issues naomi

### ISSUE THREAD

**Issue by Kelvfimer** [twinaphex/reicast-emulator#1115]
Hello

I'm using EMUELEC on odroid n2+ with Libretro Flycast. For lightgun I use mayflash bar and wiimotes. Since last updates when setting lightgun, the lightgun is only working in a small square on the left top corner of the screen on naomi games such as confidential mission.

Did you suffer similar scenario? Can you help to troubleshoot where the issue is?

thx

**Comment by flyinghead** [comment]
Have you tried doing a gun calibration in the game test menu?

**Comment by Kelvfimer** [comment]
Hello I did so I'm still having the issue. The area square is on top left... Any other suggestion I compiled the latest version ans same behaviour. thx!!

**Comment by Kelvfimer** [comment]
Hello @flyinghead with release 3b8e3113bbf45669fd5fef2a018ffe9b3ae0f6a6  it's working again :) So pls do not touch a lot the code ;) Thx SO much

**Comment by flyinghead** [comment]
Your Emuelec build is using an old version of the core. The new version is now at http://github.com/flyinghead/flycast. They will switch over if not already done. This repository is no longer maintained.

**Comment by Kelvfimer** [comment]
thx for letting me know :) Thx for your work and effort. Kind Regards.
