### ISSUE TITLE
Frame pacing/timing issue in 30fps games

### ISSUE THREAD

**Issue by ghost** [twinaphex/reicast-emulator#1124]
Edit: Issue is an upstream bug and is being investigated there in more detail: https://github.com/flyinghead/flycast/issues/520

**Comment by Nejsplitter** [comment]
@twinaphex  are you aware such issues exist on retroarch version too ? on pc and on retroarch xbox, i have tried every combination of sync settings on both platforms and frame pacing problem persists

**Comment by inactive123** [comment]
Are you talking about the core from this repository or the upstream libretro core? The upstream libretro core can be downloaded from the buildbot or Online Updater

It's hard to understand what you're talking about honestly. You need to provide more relevant information.

**Comment by Nejsplitter** [comment]
upstream libretro core latest

**Comment by DonelBueno** [comment]
I'm facing the same issue, even on a VRR monitor the experience is bad in 30 FPS games.

30 FPS game (THPS1):
![1](https://user-images.githubusercontent.com/4239694/148112576-978032ea-3111-4d32-9802-78ae2122370f.png)

60 FPS game (Vigilante 8 Second Offense):
![2](https://user-images.githubusercontent.com/4239694/148112587-7b314656-ef58-4802-b43f-6c1d43b7990a.png)

Windows 10 Pro 21H1 64 bits, Nvidia GTX 1070 with drivers 497.29, Retroarch 1.9.14 Stable 64 bits.

Threaded rendering doesn't affect the outcome.

**Comment by Nejsplitter** [comment]
Issue is an upstream bug and is being investigated there in more detail : https://github.com/flyinghead/flycast/issues/479#issue-comment-box

**Comment by Nejsplitter** [comment]
Issue is an upstream bug and is being investigated there in more detail : https://github.com/flyinghead/flycast/issues/479#issue-1091858673

**Comment by BParks21** [comment]
We need duplicate frames implemented for all renderers not just vulkan. Every emulator needs this imo. Smooth 30fps just isn't possible in Windows like it is on consoles without it. Thats why so many emulators have a duplicate frames option or do it by default. PPSSPP, Dolphin, PCSX2, Duckstation, Snes9x, ParaLLEI/Mupen, Citra now does it by default. There's a reason all of these emulators have it. It works!
