### ISSUE TITLE
Stretch Image 2D Fighting Games like Street Fighter III 3rd Strike 

### ISSUE THREAD

**Issue by yudhiyou** [twinaphex/reicast-emulator#1133]
As we know those 2D fighting games like Street Fighter III 3rd Strike, Fatal Fury Mark of the Wolves, and Street Fighter Alpha 3 are not shown fullscreen on Dreamcast. Is it possible Flycast has feature to stretch those games image to make it fullscreen?

**Comment by riggles1** [comment]
either use a shader like image-adjustment.slang to adjust horizontal size, or create a manual config override for the game with your custom screen sizes (using the settings>video>scale setting)

**Comment by yudhiyou** [comment]
> either use a shader like image-adjustment.slang to adjust horizontal size, or create a manual config override for the game with your custom screen sizes (using the settings>video>scale setting)

Ya, I want to try those setting also. I had tried it but still not successfull. Can you give me tutorial example for Street Fighter Alpha 3 dreamcast how to do that using setting>video>scale?

**Comment by yudhiyou** [comment]
I meant fullscreen is not widescreen. It is correct aspect ratio with no black border on bottom/top. I have successfully do that only on Street Fighter III 3rd Strike Dreamcast using low res code by holding Start+Y buttons.
The problem is other games don't have that low res code like Street Fighter Alpha 3 and Fatal Fury Mark of The Wolves.

**Comment by yudhiyou** [comment]
OK. I have already found solution for this issue. Using custom viewport on Retroarch video scaling setting is working perfectly.
We can save the setting per game on override game setting in quick menu.
