### ISSUE TITLE
PSO v.2 run 30fps!!

### ISSUE THREAD

**Issue by Arquivista** [twinaphex/reicast-emulator#1141]
It doesn't matter which region they are all running with the FPS locked at 30, I've already tested the same game on Redream and it runs at 60.

I also tested it on the standard Flycast emulator and it also runs at 30fps on it.

I've tried everything you can think of settings and nothing works, I believe the problem is with the core.

Core version: 514eedb (I've already tested it in 5 previous versions)
Retroarch version: 1.10.1

**Comment by flyinghead** [comment]
PSOv2 is a 30 FPS game. redream's counter is misleading.

**Comment by Arquivista** [comment]
> ‎PSOv2 é um jogo de 30 FPS. contador redream é enganoso.‎

No, it's actually running at 60fps, even if it didn't have the counter it's very obvious when a game is at 30 or 60fps.

But I added the MSI on the screen to show that it also shows as at 60fps.

I believe that if the PSO runs at 30fps at some point it should only be in multiplayer but I'm not sure.

Another option is that Redream is running wrong.
![Screenshot_2](https://user-images.githubusercontent.com/30628523/159132415-8741dd6c-ab11-4c7c-b7f3-464128ae62de.jpg)

**Comment by flyinghead** [comment]
If you think I'm lying then you should not trust my work.
And you certainly should NOT install Flycast on your machine.

Use redream instead.

**Comment by flyinghead** [comment]
https://dreamcast-talk.com/forum/viewtopic.php?t=6787

**Comment by Arquivista** [comment]
> If you think I'm lying then you should not trust my work. And you certainly should NOT install Flycast on your machine.
> 
> Use redream instead.

My native language is not English and maybe that's why I may have sounded arrogant or that I don't believe you, but I can say that this is not the case.

You said that Redream was showing wrong on his counter, I said no, the game is really at 60fps, the gameplay is VERY smooth with a perfect frame-pacing, so I could say that it wasn't Redream's counter that was wrong (in fact it is not, as I showed in the photo).

You just said the problem was because the counter was wrong (and it's not), I said then it was probably the wrong Redream.

About using Redream....personally I think it's a very good emulator too (although I prefer Flycast), but I also like achievements and unfortunately only Flycast supports it.

**Comment by dankcushions** [comment]
> so I could say that it wasn't Redream's counter that was wrong (in fact it is not, as I showed in the photo).

the counter on the screenshot probably just shows how often opengl is being told to update. it doesn't mean the underlying emulated framerate is 60fps, it could just mean that each frame is rendered twice. maybe redream updates to screen always at 60hz regardless of content to keep the UI elements smooth regardless of content, IDK. i have seen emulated 30 fps n64 games also do this on certain emulators.

PSO is 30fps for sure.
https://www.dreamcast-talk.com/forum/viewtopic.php?f=25&t=4120&start=880
https://www.reddit.com/r/PSO/comments/8h5aso/any_way_to_increase_30_fps_cap/
https://forum.beyond3d.com/posts/69693/

**Comment by ESPPIRAL** [comment]
> > If you think I'm lying then you should not trust my work. And you certainly should NOT install Flycast on your machine.
> > Use redream instead.
> 
> My native language is not English and maybe that's why I may have sounded arrogant or that I don't believe you, but I can say that this is not the case.
> 
> You said that Redream was showing wrong on his counter, I said no, the game is really at 60fps, the gameplay is VERY smooth with a perfect frame-pacing, so I could say that it wasn't Redream's counter that was wrong (in fact it is not, as I showed in the photo).
> 
> You just said the problem was because the counter was wrong (and it's not), I said then it was probably the wrong Redream.
> 
> About using Redream....personally I think it's a very good emulator too (although I prefer Flycast), but I also like achievements and unfortunately only Flycast supports it.

The game is 30 fps no matter what you see on redream, this issue should be closed.

**Comment by barbudreadmon** [comment]
@Arquivista the purpose of emulators is to reproduce original hardware the most accurately possible, PSO is a 30fps game, it has been known for 2 decades, so it's perfectly fine if it is emulated as such.

If you really think redream is emulating 60 distinct frames per second on this game, and not 30 distinct frames they are duping, then that's a redream bug and you should probably report it to them.

Closing.
